CREATE TABLE IF NOT EXISTS `body_camera_enquiries` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `pidEnquiry` VARCHAR(80) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `organisation` VARCHAR(160) NOT NULL,
  `phone` VARCHAR(40) NOT NULL,
  `country` VARCHAR(80) NOT NULL,
  `fleetSize` VARCHAR(40) NULL,
  `liveCommand` VARCHAR(40) NULL,
  `timeframe` VARCHAR(60) NULL,
  `requirements` LONGTEXT NOT NULL,
  `source` VARCHAR(200) NOT NULL DEFAULT 'body-camera-solutions',
  `status` VARCHAR(40) NOT NULL DEFAULT 'new',
  `assignedOwner` VARCHAR(160) NULL,
  `internalNotes` LONGTEXT NULL,
  `adminNotificationStatus` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `customerNotificationStatus` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `notificationError` TEXT NULL,
  `submittedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `handledAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `body_camera_enquiries_pidEnquiry_key`(`pidEnquiry`),
  INDEX `body_camera_enquiries_status_submittedAt_idx`(`status`, `submittedAt`),
  INDEX `body_camera_enquiries_email_idx`(`email`),
  INDEX `body_camera_enquiries_organisation_idx`(`organisation`),
  INDEX `body_camera_enquiries_assignedOwner_idx`(`assignedOwner`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
