import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import crypto from 'node:crypto';
function load(file,imports={}){const api={};new Function('exports','require',ts.transpileModule(fs.readFileSync(new URL('../lib/refunds/'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(api,n=>n==='server-only'?{}:n==='node:crypto'?crypto:imports[n]);return api;}
const money=load('money.ts'),references=load('paypal-reference.ts');
function engine({status='COMPLETED',pending=false,reserved='0',service='PROCUREMENT',resolved=false}={}){
 const writes=[],calls=[];const provider={id:'REFUND123',status,amount:{currency_code:'USD',value:'10.00'},links:[{rel:'up',href:'https://api-m.paypal.com/v2/payments/captures/CAPTURE123'}]};
 const tx={$queryRaw:async strings=>{const sql=strings.join('');if(sql.includes('SELECT detailsJson'))return[{detailsJson:JSON.stringify({captureId:'CAPTURE123',currency:'USD',amount:'10.00'})}];if(sql.includes('SELECT refundId FROM refund_events'))return resolved?[{refundId:'EXTERNAL_PAYPAL_REFUND123'}]:[];if(sql.includes('SELECT eventType FROM refund_events'))return[];if(sql.includes('FROM payments'))return[{pidPayment:'PAY1',pidUser:'USER1',serviceID:'ORDER1',serviceName:service,amount:100,currency:'USD'}];if(sql.includes('FROM refund_records'))return pending?[{pidRefund:'EXISTING'}]:[];if(sql.includes('SUM(amount)'))return[{amount:reserved}];if(sql.includes('FROM refund_provider_legs'))return[];throw Error(sql);},$executeRaw:async(...args)=>{writes.push(args);return 1;},refund_records:{create:async input=>writes.push(input)}};
 const imports={'@/lib/prisma':{prisma:{$transaction:fn=>fn(tx)}},'./money':money,'./paypal-reference':references,'./paypal-client':{paypalRefundRequest:async(...args)=>{calls.push(args);return provider;}}};
 return{...load('external-classification.ts',imports),...load('external-paypal.ts',imports),writes,calls};
}
const input={remainingEligiblePercent:'100',reason:'The reviewed refund relates only to procurement shipping.',confirmed:true};
test('classified procurement shipping refund records original money and retains product earnings',async()=>{const api=engine();await api.classifyExternalPayPalRefund('REFUND123','ADMIN',input);const row=api.writes.find(v=>v.data)?.data;assert.equal(row.currency,'USD');assert.equal(row.amount,'10.00');assert.equal(JSON.parse(row.ext2).productRetentionRatio,'1.00000000');assert.equal(row.refundStatus,'refunded');assert.deepEqual(api.calls,[['/refunds/REFUND123']]);});
test('invoice classification records retained shipping units without guessing from the payment percentage',async()=>{const api=engine({service:'Invoice Payment'});await api.classifyExternalPayPalRefund('REFUND123','ADMIN',{...input,remainingEligiblePercent:'75'});const row=api.writes.find(v=>v.data).data;assert.equal(row.serviceType,'SHIPPING_INVOICE');assert.equal(JSON.parse(row.ext2).productRetentionRatio,'0.75000000');});
test('pending entitlement, excessive refund capacity and unsupported services block a new classification',async()=>{for(const options of [{pending:true},{reserved:'95'},{service:'PARTNER_PROCUREMENT'},{status:'PENDING'}]){const api=engine(options);await assert.rejects(api.classifyExternalPayPalRefund('REFUND123','ADMIN',input));assert.equal(api.writes.length,0);}});
test('classification validates consent, percentages and review evidence',async()=>{for(const change of [{confirmed:false},{remainingEligiblePercent:'101'},{remainingEligiblePercent:'-1'},{remainingEligiblePercent:'NaN'},{reason:'short'}]){const api=engine();await assert.rejects(api.classifyExternalPayPalRefund('REFUND123','ADMIN',{...input,...change}));assert.equal(api.writes.length,0);}});
test('duplicate external classification cannot create another settlement',async()=>{const api=engine({resolved:true});await api.classifyExternalPayPalRefund('REFUND123','ADMIN',input);assert.equal(api.writes.length,0);});
test('failed/cancelled external review closes only after canonical provider confirmation',async()=>{for(const status of ['FAILED','CANCELLED']){const api=engine({status});await api.closeUnpaidExternalPayPalRefund('REFUND123','ADMIN');assert.equal(api.writes.length,1);assert.match(api.writes[0][0].join(''),/EXTERNAL_REFUND_NOT_PAID/);}for(const status of ['COMPLETED','PENDING']){const api=engine({status});await assert.rejects(api.closeUnpaidExternalPayPalRefund('REFUND123','ADMIN'));assert.equal(api.writes.length,0);}});
