import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync(new URL('../lib/refunds/paypal-client.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
async function run(options,fn){const calls=[];const env={SUREIMPORTS_PAYPAL_CLIENT_ID:'NEW',SUREIMPORTS_PAYPAL_SECRET:'new-secret',PAYPAL_CLIENT_ID:'OLD',PAYPAL_CLIENT_SECRET:'old-secret',PAYPAL_ENV:options.sandbox?'sandbox':'live'};const prior=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]])),fetch=globalThis.fetch;Object.assign(process.env,env);
 globalThis.fetch=async(url,request={})=>{assert.ok(url.startsWith('https://api-m.paypal.com/'));calls.push([url,request]);if(url.endsWith('/token'))return Response.json({access_token:request.headers.Authorization.includes(Buffer.from('NEW:new-secret').toString('base64'))?'NEW':'OLD'});if(request.method==='POST'){if(options.timeout)throw Error('Timeout');return Response.json({id:'REF123'});}if(request.headers.Authorization==='Bearer NEW'&&options.legacy)return Response.json({}, {status:options.outage?503:404});return Response.json({id:'CAP123'});};
 try{const api={};new Function('exports','require',source)(api,()=>({}));await fn(api,calls);}finally{globalThis.fetch=fetch;for(const [k,v]of Object.entries(prior))if(v===undefined)delete process.env[k];else process.env[k]=v;}}
test('historical refund uses the capture-owning live app and sends exactly one idempotent POST',()=>run({legacy:true},async(api,calls)=>{await api.paypalRefundRequest('/captures/CAP123/refund',{amount:{value:'10.00',currency_code:'USD'}},'RFP123');const posts=calls.filter(([url,r])=>r.method==='POST'&&!url.endsWith('/token'));assert.equal(posts.length,1);assert.equal(posts[0][1].headers.Authorization,'Bearer OLD');assert.equal(posts[0][1].headers['PayPal-Request-Id'],'RFP123');}));
test('provider outage is not mistaken for a legacy capture',()=>run({legacy:true,outage:true},async(api,calls)=>{await assert.rejects(api.paypalRefundRequest('/captures/CAP123'));assert.equal(calls.filter(([url])=>url.endsWith('/token')).length,1);}));
test('a refund POST timeout never triggers another app or another POST',()=>run({timeout:true},async(api,calls)=>{await assert.rejects(api.paypalRefundRequest('/captures/CAP123/refund',{},'RFP123'),/Timeout/);assert.equal(calls.filter(([url,r])=>r.method==='POST'&&!url.endsWith('/token')).length,1);}));
test('sandbox legacy credentials cannot settle live records',()=>run({legacy:true,sandbox:true},async(api,calls)=>{await assert.rejects(api.paypalRefundRequest('/captures/CAP123'),/could not be found/);assert.equal(calls.filter(([url])=>url.endsWith('/token')).length,1);}));
