CREATE TABLE IF NOT EXISTS `marketing_leads` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `pidLead` VARCHAR(191) NOT NULL,
  `firstName` VARCHAR(100) NULL,
  `email` VARCHAR(255) NOT NULL,
  `segmentId` VARCHAR(100) NULL,
  `source` VARCHAR(100) NULL,
  `pageType` VARCHAR(50) NULL,
  `pageUrl` TEXT NULL,
  `pathname` VARCHAR(500) NULL,
  `referrer` TEXT NULL,
  `utmSource` VARCHAR(255) NULL,
  `utmMedium` VARCHAR(255) NULL,
  `utmCampaign` VARCHAR(255) NULL,
  `utmContent` VARCHAR(255) NULL,
  `utmTerm` VARCHAR(255) NULL,
  `fbclid` TEXT NULL,
  `fbp` VARCHAR(255) NULL,
  `fbc` VARCHAR(255) NULL,
  `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NULL,

  UNIQUE INDEX `marketing_leads_pidLead_key`(`pidLead`),
  INDEX `marketing_leads_email_idx`(`email`),
  INDEX `marketing_leads_createdAt_idx`(`createdAt`),
  INDEX `marketing_leads_pageType_idx`(`pageType`),
  INDEX `marketing_leads_pathname_idx`(`pathname`),
  INDEX `marketing_leads_utmSource_idx`(`utmSource`),
  INDEX `marketing_leads_utmCampaign_idx`(`utmCampaign`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
