CREATE TABLE IF NOT EXISTS `consultation_bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidBooking` VARCHAR(80) NOT NULL,
  `manageToken` VARCHAR(160) NOT NULL,
  `fullName` VARCHAR(180) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(80) NULL,
  `businessName` VARCHAR(180) NULL,
  `consultationGoal` LONGTEXT NULL,
  `timezoneLabel` VARCHAR(80) NOT NULL DEFAULT 'Africa/Lagos',
  `slotStartUtc` DATETIME(3) NOT NULL,
  `slotEndUtc` DATETIME(3) NOT NULL,
  `durationMinutes` INT NOT NULL DEFAULT 30,
  `status` VARCHAR(40) NOT NULL DEFAULT 'pending_payment',
  `amountKobo` INT NOT NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'NGN',
  `paystackReference` VARCHAR(120) NULL,
  `paystackCustomerCode` VARCHAR(120) NULL,
  `paidAt` DATETIME(3) NULL,
  `zoomMeetingId` VARCHAR(120) NULL,
  `zoomJoinUrl` VARCHAR(1200) NULL,
  `zoomStartUrl` VARCHAR(1200) NULL,
  `assignedOwner` VARCHAR(180) NULL,
  `callOutcomeStatus` VARCHAR(40) NULL,
  `outcomeFeedback` LONGTEXT NULL,
  `nextFollowUpAt` DATETIME(3) NULL,
  `cancelReason` VARCHAR(500) NULL,
  `cancelledAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `consultation_bookings_pidBooking_key` (`pidBooking`),
  UNIQUE INDEX `consultation_bookings_manageToken_key` (`manageToken`),
  UNIQUE INDEX `consultation_bookings_paystackReference_key` (`paystackReference`),
  INDEX `consultation_bookings_email_idx` (`email`),
  INDEX `consultation_bookings_status_idx` (`status`),
  INDEX `consultation_bookings_slotStartUtc_idx` (`slotStartUtc`)
);
