-- CreateTable
CREATE TABLE `corporate_gift_request` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `pidRequest` VARCHAR(191) NOT NULL,
    `businessName` VARCHAR(191) NOT NULL,
    `contactPersonFullName` VARCHAR(191) NOT NULL,
    `productOrItemNeeded` VARCHAR(191) NOT NULL,
    `detailedSpecifications` LONGTEXT NOT NULL,
    `quantityNeeded` INTEGER NOT NULL,
    `preferredQualityLevel` VARCHAR(191) NOT NULL,
    `brandingCustomizationRequired` VARCHAR(191) NOT NULL,
    `expectedDeliveryDate` VARCHAR(191) NOT NULL,
    `finalDeliveryLocationNigeria` VARCHAR(191) NOT NULL,
    `contactEmail` VARCHAR(191) NOT NULL,
    `whatsappNumber` VARCHAR(191) NOT NULL,
    `proceedTimeline` VARCHAR(191) NULL,
    `hearAboutSureImports` VARCHAR(191) NULL,
    `additionalNotes` LONGTEXT NULL,
    `budgetRange` VARCHAR(191) NULL,
    `referenceFileUrl` VARCHAR(191) NULL,
    `referenceFileName` VARCHAR(191) NULL,
    `logoFileUrl` VARCHAR(191) NULL,
    `logoFileName` VARCHAR(191) NULL,
    `pageUrl` VARCHAR(191) NULL,
    `utmSource` VARCHAR(191) NULL,
    `utmMedium` VARCHAR(191) NULL,
    `utmCampaign` VARCHAR(191) NULL,
    `utmContent` VARCHAR(191) NULL,
    `utmTerm` VARCHAR(191) NULL,
    `submittedAt` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `corporate_gift_request_pidRequest_key`(`pidRequest`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
