import WhatsAppButton from '@/components/WhatsAppButton';
import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'sure imports',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        {children}
        <WhatsAppButton
          waID="CUR7YKW3K3RBA1"
          message="Hello! I'd like to ask about your services."
          position="bottom-left"
        />
      </body>
    </html>
  );
}
