import type { Metadata } from 'next';
import './globals.css';
//import Footer from '@/components/home/Footer';
import NavBar from '@/components/home/NavBar';
import { CookieConsent } from '@/components/home/CookieConsent';
import WhatsAppButton from '@/components/WhatsAppButton';
import ScrollToTopButton from '@/components/home/scrollToTopButton';
import Header from '@/app/(home)/components/Navigation';
import Footer from '@/app/(home)/components/Footer';
import { useEffect, useState } from 'react';

export const metadata: Metadata = {
  title: 'Sure Imports',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="relative">
        <Header />
        {/* <LiveChatWidgetComponent /> */}
        {children}
        <CookieConsent />
        {/* Add the WhatsApp button */}
        <WhatsAppButton
          waID="CUR7YKW3K3RBA1"
          message="Hello! I'd like to ask about your services."
          position="bottom-left"
        />
        {/* <LiveChat /> */}
        <Footer />
        {/* <ScrollToTopButton /> */}
      </div>
    </>
  );
}
