CREATE TABLE IF NOT EXISTS `intelligence_review_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidRequest` VARCHAR(80) NOT NULL,
  `pidUser` VARCHAR(191) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `requestType` VARCHAR(60) NOT NULL,
  `nicheSlug` VARCHAR(180) NULL,
  `nicheName` VARCHAR(180) NULL,
  `supplierName` VARCHAR(180) NULL,
  `supplierWebsite` VARCHAR(500) NULL,
  `supplierContact` VARCHAR(500) NULL,
  `productDetails` LONGTEXT NULL,
  `quoteDetails` LONGTEXT NULL,
  `targetQuantity` VARCHAR(120) NULL,
  `budgetRange` VARCHAR(180) NULL,
  `decisionNeeded` LONGTEXT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'submitted',
  `adminResponse` LONGTEXT NULL,
  `adminRecommendations` LONGTEXT NULL,
  `adminRiskLevel` VARCHAR(40) NULL,
  `reviewedByPidUser` VARCHAR(191) NULL,
  `reviewedByEmail` VARCHAR(255) NULL,
  `reviewedByName` VARCHAR(180) NULL,
  `reviewedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `intelligence_review_requests_pidRequest_key` (`pidRequest`),
  INDEX `intelligence_review_requests_pidUser_idx` (`pidUser`),
  INDEX `intelligence_review_requests_email_idx` (`email`),
  INDEX `intelligence_review_requests_status_idx` (`status`),
  INDEX `intelligence_review_requests_requestType_idx` (`requestType`),
  INDEX `intelligence_review_requests_createdAt_idx` (`createdAt`)
);
