-- Supplier Intelligence one-time report products, immutable editions, and purchases.
CREATE TABLE IF NOT EXISTS `intelligence_report_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidReport` VARCHAR(80) NOT NULL,
  `nicheId` VARCHAR(80) NOT NULL,
  `slug` VARCHAR(180) NOT NULL,
  `title` VARCHAR(220) NOT NULL,
  `subtitle` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `editionLabel` VARCHAR(120) NOT NULL,
  `coverImageUrl` VARCHAR(1000) NULL,
  `priceNaira` INT NOT NULL,
  `priceUsdCents` INT NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `currentVersionId` VARCHAR(80) NULL,
  `supplierCount` INT NOT NULL DEFAULT 0,
  `publishedAt` DATETIME(3) NULL,
  `createdByPidUser` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `intelligence_report_products_pidReport_key`(`pidReport`),
  UNIQUE INDEX `intelligence_report_products_nicheId_key`(`nicheId`),
  UNIQUE INDEX `intelligence_report_products_slug_key`(`slug`),
  INDEX `intelligence_report_products_status_publishedAt_idx`(`status`, `publishedAt`),
  INDEX `intelligence_report_products_currentVersionId_idx`(`currentVersionId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `intelligence_report_versions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidVersion` VARCHAR(80) NOT NULL,
  `reportId` VARCHAR(80) NOT NULL,
  `versionNumber` INT NOT NULL,
  `editionLabel` VARCHAR(120) NOT NULL,
  `supplierSnapshot` JSON NOT NULL,
  `supplierCount` INT NOT NULL DEFAULT 0,
  `pdfUrl` VARCHAR(1000) NULL,
  `pdfPublicId` VARCHAR(500) NULL,
  `fileBytes` INT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'generated',
  `generatedByPidUser` VARCHAR(191) NULL,
  `generatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `approvedAt` DATETIME(3) NULL,
  `publishedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `intelligence_report_versions_pidVersion_key`(`pidVersion`),
  UNIQUE INDEX `intelligence_report_versions_reportId_versionNumber_key`(`reportId`, `versionNumber`),
  INDEX `intelligence_report_versions_reportId_status_idx`(`reportId`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `intelligence_report_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidOrder` VARCHAR(80) NOT NULL,
  `reportId` VARCHAR(80) NOT NULL,
  `versionId` VARCHAR(80) NOT NULL,
  `pidUser` VARCHAR(191) NULL,
  `email` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(120) NULL,
  `lastName` VARCHAR(120) NULL,
  `billingCountry` VARCHAR(120) NULL,
  `paymentProvider` VARCHAR(40) NOT NULL,
  `providerReference` VARCHAR(160) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `amountMinor` INT NOT NULL,
  `currency` VARCHAR(10) NOT NULL,
  `downloadToken` VARCHAR(160) NOT NULL,
  `downloadCount` INT NOT NULL DEFAULT 0,
  `paidAt` DATETIME(3) NULL,
  `fulfilledAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `intelligence_report_orders_pidOrder_key`(`pidOrder`),
  UNIQUE INDEX `intelligence_report_orders_providerReference_key`(`providerReference`),
  UNIQUE INDEX `intelligence_report_orders_downloadToken_key`(`downloadToken`),
  INDEX `intelligence_report_orders_reportId_status_idx`(`reportId`, `status`),
  INDEX `intelligence_report_orders_versionId_idx`(`versionId`),
  INDEX `intelligence_report_orders_pidUser_status_idx`(`pidUser`, `status`),
  INDEX `intelligence_report_orders_email_status_idx`(`email`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

