CREATE TABLE IF NOT EXISTS `search_console_import_runs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidRun` VARCHAR(80) NOT NULL,
  `siteUrl` VARCHAR(255) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `dimensions` VARCHAR(255) NOT NULL,
  `rowCount` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(40) NOT NULL DEFAULT 'started',
  `errorMessage` TEXT NULL,
  `startedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completedAt` DATETIME NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `search_console_import_runs_pidRun_key` (`pidRun`),
  KEY `search_console_import_runs_siteUrl_idx` (`siteUrl`),
  KEY `search_console_import_runs_status_idx` (`status`),
  KEY `search_console_import_runs_startDate_endDate_idx` (`startDate`, `endDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `search_console_query_stats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidStat` VARCHAR(80) NOT NULL,
  `date` DATETIME NOT NULL,
  `siteUrl` VARCHAR(255) NOT NULL,
  `pageUrl` TEXT NOT NULL,
  `query` VARCHAR(700) NOT NULL,
  `country` VARCHAR(20) NULL,
  `device` VARCHAR(40) NULL,
  `clicks` INT NOT NULL DEFAULT 0,
  `impressions` INT NOT NULL DEFAULT 0,
  `ctr` DECIMAL(12, 8) NOT NULL DEFAULT 0,
  `position` DECIMAL(12, 4) NOT NULL DEFAULT 0,
  `runId` VARCHAR(80) NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `search_console_query_stats_pidStat_key` (`pidStat`),
  UNIQUE KEY `uniq_gsc_daily_page_query` (`date`, `siteUrl`, `pageUrl`(255), `query`(255), `country`, `device`),
  KEY `search_console_query_stats_date_idx` (`date`),
  KEY `search_console_query_stats_siteUrl_idx` (`siteUrl`),
  KEY `search_console_query_stats_query_idx` (`query`),
  KEY `search_console_query_stats_country_idx` (`country`),
  KEY `search_console_query_stats_device_idx` (`device`),
  KEY `search_console_query_stats_runId_idx` (`runId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `seo_opportunities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidOpportunity` VARCHAR(80) NOT NULL,
  `pageUrl` TEXT NOT NULL,
  `blogSlug` VARCHAR(500) NULL,
  `opportunityType` VARCHAR(80) NOT NULL,
  `primaryQuery` VARCHAR(700) NULL,
  `queryCluster` LONGTEXT NULL,
  `clicks` INT NOT NULL DEFAULT 0,
  `impressions` INT NOT NULL DEFAULT 0,
  `ctr` DECIMAL(12, 8) NOT NULL DEFAULT 0,
  `position` DECIMAL(12, 4) NOT NULL DEFAULT 0,
  `confidence` DECIMAL(5, 4) NOT NULL DEFAULT 0,
  `status` VARCHAR(40) NOT NULL DEFAULT 'open',
  `recommendation` LONGTEXT NULL,
  `recommendedCta` VARCHAR(120) NULL,
  `sourceStartDate` DATETIME NULL,
  `sourceEndDate` DATETIME NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `seo_opportunities_pidOpportunity_key` (`pidOpportunity`),
  KEY `seo_opportunities_blogSlug_idx` (`blogSlug`),
  KEY `seo_opportunities_opportunityType_idx` (`opportunityType`),
  KEY `seo_opportunities_status_idx` (`status`),
  KEY `seo_opportunities_createdAt_idx` (`createdAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `seo_content_change_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidChange` VARCHAR(80) NOT NULL,
  `pidOpportunity` VARCHAR(80) NULL,
  `pidBlog` VARCHAR(80) NULL,
  `changeType` VARCHAR(80) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `beforeJson` LONGTEXT NULL,
  `afterJson` LONGTEXT NULL,
  `validationJson` LONGTEXT NULL,
  `publishedAt` DATETIME NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `seo_content_change_logs_pidChange_key` (`pidChange`),
  KEY `seo_content_change_logs_pidOpportunity_idx` (`pidOpportunity`),
  KEY `seo_content_change_logs_pidBlog_idx` (`pidBlog`),
  KEY `seo_content_change_logs_changeType_idx` (`changeType`),
  KEY `seo_content_change_logs_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
