CREATE TABLE `procurement_partner_customer_orders` (
  `id` VARCHAR(80) NOT NULL,
  `partnerId` VARCHAR(191) NOT NULL,
  `customerPidUser` VARCHAR(191) NOT NULL,
  `idempotencyKey` VARCHAR(100) NOT NULL,
  `payloadHash` CHAR(64) NOT NULL,
  `detailsCiphertext` LONGTEXT NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'saved',
  `revision` INTEGER NOT NULL DEFAULT 1,
  `paymentStatus` VARCHAR(24) NOT NULL DEFAULT 'UNPAID',
  `verifiedPaymentReference` VARCHAR(191) NULL,
  `paidRevision` INTEGER NULL,
  `partnerReview` VARCHAR(24) NOT NULL DEFAULT 'NOT_READY',
  `approvedAt` DATETIME(3) NULL,
  `releasedOrderId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `partner_customer_retry_key` (`partnerId`, `customerPidUser`, `idempotencyKey`),
  UNIQUE INDEX `partner_customer_payment_key` (`verifiedPaymentReference`),
  UNIQUE INDEX `partner_customer_release_key` (`releasedOrderId`),
  INDEX `partner_customer_order_owner_idx` (`partnerId`, `customerPidUser`, `createdAt`),
  INDEX `partner_customer_review_idx` (`partnerId`, `paymentStatus`, `partnerReview`),
  CONSTRAINT `partner_customer_order_partner_fk` FOREIGN KEY (`partnerId`) REFERENCES `procurement_partners` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
