CREATE TABLE shop_checkouts (
  reference VARCHAR(100) NOT NULL PRIMARY KEY,
  pidUser VARCHAR(191) NOT NULL,
  requestKey VARCHAR(36) NOT NULL,
  requestHash VARCHAR(64) NOT NULL,
  provider VARCHAR(16) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  email VARCHAR(191) NOT NULL,
  customerName VARCHAR(191) NOT NULL,
  shippingAddress TEXT NOT NULL,
  items JSON NOT NULL,
  amountMinor DOUBLE NOT NULL,
  authorizationUrl TEXT NULL,
  accessCode VARCHAR(191) NULL,
  initializationStartedAt DATETIME(3) NULL,
  paidAt DATETIME(3) NULL,
  affiliateDoneAt DATETIME(3) NULL,
  customerEmailSentAt DATETIME(3) NULL,
  adminEmailSentAt DATETIME(3) NULL,
  effectsLeaseUntil DATETIME(3) NULL,
  lastCheckedAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY shop_checkout_request (pidUser, requestKey),
  KEY shop_checkout_recovery (status, lastCheckedAt),
  KEY shop_checkout_customer (pidUser, createdAt)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
