CREATE TABLE IF NOT EXISTS `blog_lead_magnets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pidMagnet` VARCHAR(80) NOT NULL,
  `pidBlog` VARCHAR(80) NOT NULL,
  `blogSlug` VARCHAR(500) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `title` VARCHAR(255) NOT NULL,
  `offerHeadline` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `buttonText` VARCHAR(120) NULL,
  `bulletsJson` LONGTEXT NULL,
  `emailSubject` VARCHAR(255) NULL,
  `deliveryMessage` TEXT NULL,
  `pdfJson` LONGTEXT NULL,
  `recommendedCta` VARCHAR(120) NULL,
  `sourceQuery` VARCHAR(700) NULL,
  `model` VARCHAR(120) NULL,
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `blog_lead_magnets_pidMagnet_key` (`pidMagnet`),
  UNIQUE KEY `blog_lead_magnets_pidBlog_key` (`pidBlog`),
  UNIQUE KEY `blog_lead_magnets_slug_key` (`slug`),
  KEY `blog_lead_magnets_status_idx` (`status`),
  KEY `blog_lead_magnets_pidBlog_status_idx` (`pidBlog`, `status`),
  KEY `blog_lead_magnets_blogSlug_idx` (`blogSlug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
